version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_list_api_dev
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
